### ISSUE TITLE
Integrate usage analytics

### ISSUE THREAD

**Issue by Popolechien** [offspot/package-requests#16]
https://plausible.io/ is a potential candidate.

**Comment by kelson42** [comment]
@Bastien-BSF I really believe this is something we could/should have in common. I know you are ahead on this topic with OLIP. Do you have a description somewhere, or any pointer, allowing us how you deal with usage analytics within OLIP?

**Comment by kelson42** [comment]
@Popolechien How is this ticket different from #17?

**Comment by Popolechien** [comment]
@kelson42 Looks like the same.

**Comment by kelson42** [comment]
closing in favour of #17

**Comment by Bastien-BSF** [comment]
@kelson42 I do agree that we should have this in common.

As far as I am aware, OLIP is desperately lacking an analytics tool. We are experiencing difficulties in reporting back about the actual usage of OLIP to our partners.

The only solution we have in place right now is an instance of https://github.com/netdata/netdata which is a system tool that, obviously, accurately reports about the **system** usage and completely fails to address the **application** usage.

Any advancement in this field would be beneficial for us as well.

**Comment by rgaudin** [comment]
My understandding was that
- you used to collect raw webserver logs and upload them using your VPN.
- more recently, you implemented GoAccess for OLIP _admins_ but were not happy with it.

Can you or @letompouce elaborate?

**Comment by Bastien-BSF** [comment]
Sorry I meant GoAccess, not Netdata.

And yes, you are right about collecting logs via VPN.

We do not build any meaningful report based on those.
