### ISSUE TITLE
Life Bible

### ISSUE THREAD

**Issue by Popolechien** [offspot/package-requests#32]
- Website/Repository URL: https://f-droid.org/en/packages/org.hlwd.bible_multi_the_life/
- License: GPL 3.0
- Desired Title: The Life Bible
- Desired Description: Bible app with multi languages support, works offline
- Desired PNG Icon (URL or attach one): https://f-droid.org/repo/org.hlwd.bible_multi_the_life/en-US/icon_k9kBtleXut0uMIg7nTpbwq8C5O6W7s0wcNRbmvqjqbw=.png
- Language(s) (ISO 639-3): **eng**
- Docker image(s) available?  No 
- Docker image or binary available for `arm64` ? 
- Update Strategy: Original translation has not been updated in a couple hundred years. App update seems to be every 3-6 months to add new language support ([changelog](https://gitlab.com/hotlittlewhitedog/BibleTheLife/-/blob/master/CHANGELOG)).

**Comment by rgaudin** [comment]
Added in https://github.com/offspot/offspot-config/commit/71db2978d60b6effaf9c86168b48134842d2928b
