### ISSUE TITLE
Magoe Education Guinée

### ISSUE THREAD

**Issue by rgaudin** [offspot/package-requests#34]
- Website/Repository URL: https://magoe.fr/
- License: TBD / FO 
- Desired Title: TBD
- Desired Description: TBD
- Desired PNG Icon (URL or attach one): TBD
- Language(s) (ISO 639-3): **fra**
- Docker image(s) available? No
- Docker image or binary available for `arm64` ? No
- Update Strategy: TBD

---

Application custom PHP/MySQL avec des cours en ligne, des QCMs, etc.
On ne dispose que d'un ZIP avec le code de l'appli, les fichiers medias et un dump de la BDD.

Nécessité de contacter le développeur:
- utiliser SQLite au lieu de MySQL (rien ne semble nécessiter mysql)
- Aucune documentation:
  - comment configurer la BDD
  - les autres informations
  - L'URL d'acces (si des liens sont générés, etc)
  - quels modules/extensions/configurations de PHP nécessaires)
  - Quels chemins doivent être servis directement (par le webserver et non PHP)
- optimiser les images. Les images de `niveau/` par exemple sont très lourdes et grandes: 2920x1521@300ppi pour 5.5MB.
- le dossier `imgUpload` contient de nombreuses photos (bitmap donc) mais sont stockées en PNG ce qui nécessite beaucoup plus d'espace. Dans ce dossier, il existe de nombreux doublons

**Comment by Mazoughou-cpu** [comment]
- utiliser SQLite au lieu de MySQL (rien ne semble nécessiter mysql) (_**l'application est développée pour le web. Personnellement je ne sais comment SQLite peut être utilisé pour le web**_)
- Aucune documentation (_**OK, nous allons vous la fournir dans le plus bref delais**_):
- comment configurer la BDD
- les autres informations
- L'URL d'acces (si des liens sont générés, etc)
- quels modules/extensions/configurations de PHP nécessaires)
- Quels chemins doivent être servis directement (par le webserver et non PHP)
- optimiser les images. Les images de niveau/ par exemple sont très lourdes et grandes: 2920x1521@300ppi pour 5.5MB **_(nous allons voir ça)._**
- le dossier imgUpload contient de nombreuses photos (bitmap donc) mais sont stockées en PNG ce qui nécessite beaucoup plus d'espace. Dans ce dossier, il existe de nombreux doublons _(**le problème que nous avons du importer les images manuellement, alors qu'au début, le code avait été écrit de sorte qu'elles soient importées automatiquement)**_

**Comment by rgaudin** [comment]
> * utiliser SQLite au lieu de MySQL (rien ne semble nécessiter mysql) (_**l'application est développée pour le web. Personnellement je ne sais comment SQLite peut être utilisé pour le web**_)

Dans `accesBDD.php`, il y a par exemple:

```php
$bdd = new PDO('mysql:host=localhost;dbname=db_fondation_orange;charset=utf8', 'root', '');
```

Je pense qu'il suffit de modifier par quelque chose comme ça où `__DIR__."/db_fondation_orange.sqlite"` est le chemin vers le fichier SQLite qui contiendra la BDD. Il existe des outils graphiques et en ligne de commande pour manipuler la BDD et importer vos dumps.

```php
 $bdd = new PDO("sqlite:".__DIR__."/db_fondation_orange.sqlite");
```

**Comment by Mazoughou-cpu** [comment]
> > * utiliser SQLite au lieu de MySQL (rien ne semble nécessiter mysql) (_**l'application est développée pour le web. Personnellement je ne sais comment SQLite peut être utilisé pour le web**_)
> 
> Dans `accesBDD.php`, il y a par exemple:
> 
> ```
> $bdd = new PDO('mysql:host=localhost;dbname=db_fondation_orange;charset=utf8', 'root', '');
> ```
> 
> Je pense qu'il suffit de modifier par quelque chose comme ça où `__DIR__."/db_fondation_orange.sqlite"` est le chemin vers le fichier SQLite qui contiendra la BDD. Il existe des outils graphiques et en ligne de commande pour manipuler la BDD et importer vos dumps.
> 
> ```
>  $bdd = new PDO("sqlite:".__DIR__."/db_fondation_orange.sqlite");
> ```

Mais base de donnée en MYSQL, comment la convertir en SQLITE ?

**Comment by Mazoughou-cpu** [comment]
> > > * utiliser SQLite au lieu de MySQL (rien ne semble nécessiter mysql) (_**l'application est développée pour le web. Personnellement je ne sais comment SQLite peut être utilisé pour le web**_)
> > 
> > 
> > Dans `accesBDD.php`, il y a par exemple:
> > ```
> > $bdd = new PDO('mysql:host=localhost;dbname=db_fondation_orange;charset=utf8', 'root', '');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Je pense qu'il suffit de modifier par quelque chose comme ça où `__DIR__."/db_fondation_orange.sqlite"` est le chemin vers le fichier SQLite qui contiendra la BDD. Il existe des outils graphiques et en ligne de commande pour manipuler la BDD et importer vos dumps.
> > ```
> >  $bdd = new PDO("sqlite:".__DIR__."/db_fondation_orange.sqlite");
> > ```
> 
> Mais base de donnée en MYSQL, comment la convertir en SQLITE ?

Je vais faire des recherches sur comment migrer de MYSQL vers SQLITE. Si je rencontre des soucis, je vous le ferai part

**Comment by Mazoughou-cpu** [comment]
> * Website/Repository URL: https://magoe.fr/
> * License: TBD / FO
> * Desired Title: TBD
> * Desired Description: TBD
> * Desired PNG Icon (URL or attach one): TBD
> * Language(s) (ISO 639-3): **fra**
> * Docker image(s) available? No
> * Docker image or binary available for `arm64` ? No
> * Update Strategy: TBD
> 
> Application custom PHP/MySQL avec des cours en ligne, des QCMs, etc. On ne dispose que d'un ZIP avec le code de l'appli, les fichiers medias et un dump de la BDD.
> 
> Nécessité de contacter le développeur:
> 
> * utiliser SQLite au lieu de MySQL (rien ne semble nécessiter mysql)
> * Aucune documentation:
>   
>   * comment configurer la BDD
>   * les autres informations
>   * L'URL d'acces (si des liens sont générés, etc)
>   * quels modules/extensions/configurations de PHP nécessaires)
>   * Quels chemins doivent être servis directement (par le webserver et non PHP)
> * optimiser les images. Les images de `niveau/` par exemple sont très lourdes et grandes: 2920x1521@300ppi pour 5.5MB.
> * le dossier `imgUpload` contient de nombreuses photos (bitmap donc) mais sont stockées en PNG ce qui nécessite beaucoup plus d'espace. Dans ce dossier, il existe de nombreux doublons

- J'ai fini l'optimisation des images. J'ai également nettoyé le dossier "imgUpLoad"
- Je suis parvenu à installer SQLite et à créer la base de données. Mais pour l'instant, je ne suis pas parvenu à importer les tables dans la base de données SQLite, c'est ma 1ère fois de faire un travail pareil. Je continue les recherches. Mais si vous pouvez me donner un coup de mains, ça me ferait plaisir.
- Pour la documentation, je veux attendre après transfert des données sur SQLite

**Comment by rgaudin** [comment]
OK très bien ;

Pour ce qui est d'importer les données, je pense qu'il faut refaire un export en excluant les fonctionnalités propres à MySQL. Pour obtenir un format SQL le plus standard possible.
Ensuite, il suffit d'executer le(s) fichier SQL obtenus ; soit en ligne de commande `sqlite3 mago.db < dump.db`, soit via un outil graphique ([sqlitebrowser](https://sqlitebrowser.org/) par exemple)

**Comment by Mazoughou-cpu** [comment]
Finalement j'ai pu travailler avec SQLite. Je vais vous ramener les fichier d'ici demain

**Comment by rgaudin** [comment]
@Mazoughou-cpu désolé pour l'attente, j'ai enfin pu regarder. Pour ce qui est de SQLite, ça semble fonctionner correctement ; merci!

Par contre, il y a **beaucoup** d'erreurs: des fichiers appelés qui n'existent pas notamment. J'en ai corrigé quelques uns (lorsque le fichier existe, mais ailleurs) mais je ne peux pas m'occuper de tous car il faudrait tester toutes les pages et surtout il y a des fichiers qui manquent.

La seule autre modification que j'ai faite concerne l'adresse attendue (`$rootLink`) qui n'est plus en dur mais qui est désormais `getenv('MAGOE_URL')`. Elle utilise donc la variable d'environnement `MAGOE_URL` à la place.

Merci de télécharger [le dossier](https://drive.offspot.it/magoe/magoe_fr_2023-11.zip) et de corriger tout ce qui peut l'être.
Pour vérifier (ou pour corriger), le plus efficace est d'utiliser Docker (cf. https://docs.docker.com/engine/install/ si tu ne l'utilise pas) en _montant_ le fameux dossier:

```sh
docker run -it -e MAGOE_URL=http://localhost:8888 -p 8888:80 -v /ton/chemin/magoe:/var/www/localhost/htdocs ghcr.io/offspot/magoe:dev
```

Avec cette commande (à modifier):

- Magoe est visible sur http://localhost:8888
- Le dossier `/ton/chemin/magoe` est utilisé

---

À coté de ça, et c'est indispensable, il nous faut les métadonnées pour que l'App rentre dans le catalogue:

- Une icone en 48x48px PNG
- Un titre (max 30 caractères)
- Une description (max 80 caractères)
- Une description plus longue (optionnelle)

**Comment by Mazoughou-cpu** [comment]
[Méta données.docx](https://github.com/offspot/package-requests/files/13629014/Meta.donnees.docx)
![logo_magoe_education_48x48](https://github.com/offspot/package-requests/assets/62692680/3d3f57b8-1ed3-406c-89a1-848901d0e4c4)

**Comment by Mazoughou-cpu** [comment]
Bonjour!
Je pense avoir fait les corrections conformément aux recommandations.
Voici donc en pièce jointe:
- le dossier corrigé, 
- l'icone en 48x48px en format png
- le fichier contenant les métadonnées comme le titre et différentes description
S'il y a de nouvel éléments à ajouter ou à corrigé, je reste toujours à votre disposition.
Cordialement!

**Comment by Mazoughou-cpu** [comment]
le dossier corrigé est disponible ici : https://drive.google.com/file/d/1zWqisTBHCV99n3tTf-WtLS9WiCRzEiIT/view?usp=sharing

**Comment by rgaudin** [comment]
Merci ; c'est intégré
