### ISSUE TITLE
Trailsense package not displaying correctly

### ISSUE THREAD

**Issue by Popolechien** [offspot/package-requests#42]
Currently on demo.hotspot.kiwix.org and trying to access the Trailsense app from the dashboard I get an error message:
![image](https://github.com/offspot/package-requests/assets/21675885/a3e4eb6e-b918-47bc-8dd3-8045235619ac)

**Comment by rgaudin** [comment]
demo is currently in maintenance mode so that's normal. I don't think it's wise, in general, to open app-related tickets from demo behavior. I'd say that when an app doesn't work, it should be a ticket for demo (k8s repo). Does that make sense?
