### ISSUE TITLE
Add LIVE (real-time) collaboration tools like Etherpad and Jitsi servers

### ISSUE THREAD

**Issue by zblace** [offspot/package-requests#5]
Hi! 
It would be awesome if kiwix-hotspot could include optional LIVE (real-time) collaboration tools like Etherpad and Jitsi servers that could be used to do and demo workflow of education/ collaborations in physical proximity (with pandemic minimum distance). Anyone interested to work on this?

Best Z

**Comment by rgaudin** [comment]
This ticket discusses 2 different apps. @zblace (or anyone interested), please open individual tickets for those you're interested in. Discussion and implementation are different and individual.

I am closing this because it's not clear from this conversation.

**Comment by rgaudin** [comment]
`question` tickets are still permitted to discuss what apps to choose to fulfill a need. Etherpad and Jitsi are too different to be considered competitors here
