### ISSUE TITLE
Considering introducing Kolibri to the software with integrate

### ISSUE THREAD

**Issue by rgaudin** [offspot/package-requests#7]
In GitLab by @Kelson42 on Jan 20, 2019, 09:50

**Comment by rgaudin** [comment]
@kelson42 @Popolechien this ticket is titled for Kolibri but the comments refers to KA-Lite. We've already dropped KA-Lite in favor of a kolibri2zim khan-academy.

Is there an interest in having kolibri on the hotspot ? In itself, it's useless but we could either:
- select some content and load them into kolibri. This would require kolibri-specific work and maintenance, not to mention the catalog integration issue.
- select some content and create ZIMs of them using kolibri2zim

I lean towards the latter, at least until we have real use-cases with kolibri-specific features.

Closing then ; please reopen if you believe we shoudl consider kolibri.

**Comment by Popolechien** [comment]
I'm in discussions with the content person at Endless and suspect the second option could be of interest to them. But let's cross that bridge when we're there.

**Comment by kelson42** [comment]
Same feedback on my side: important but not urgent.
